apiVersion: v1
entries:
  jerney:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-06-03T15:17:15.000083142+05:30"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.x.x
    description: A Helm chart for Kubernetes deployment of the Jerney Blog Platform
    digest: f58c88318fa0ac72188be6e4d119419e17985fb973bfdd6bcfe6b9a6ecde156c
    name: jerney
    type: application
    urls:
    - jerney-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-03T15:17:14.985897885+05:30"
