apiVersion: v1
entries:
  jerney:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-06-03T15:39:11.056400238+05:30"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.x.x
    description: A Helm chart for Kubernetes deployment of the Jerney Blog Platform
    digest: ca3a0a23279e01db888218986a7a5eca39ddc80cc4d6df844380c94af1205ee9
    name: jerney
    type: application
    urls:
    - https://nilkanthmiyani.github.io/jerney-devops/jerney-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-03T15:39:11.051752434+05:30"
