# Default values for jerney.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount is managed by HPA
# replicaCount:
#   backend: 2
#   frontend: 2

hpa:
  frontend:
    minReplicas: 2
    maxReplicas: 10
    targetCPU: 50
  backend:
    minReplicas: 2
    maxReplicas: 10
    targetCPU: 50
image:
  backend:
    repository: docker.io/nmiyani/jerney-backend
    tag: 20db548
  frontend:
    repository: docker.io/nmiyani/jerney-frontend
    tag: 20db548
postgresql:
  enabled: true
  image:
    tag: "latest"
  auth:
    username: jerney_user
    password: jerney_pass_2026
    database: jerney_db
  primary:
    persistence:
      size: 10Gi
      storageClass: "" # Uses cluster default (local-path on kubeadm)
otel:
  endpoint: http://signoz-otel-collector.platform.svc.cluster.local:4317
service:
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 8080
  backend:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  db:
    type: ClusterIP
    port: 5432
    targetPort: 5432
# Ingress configuration
ingress:
  enabled: true
  host: jerney.nilkanthprojects.site
  clusterIssuer: letsencrypt-prod
